<?php

/**
 * The main file for multichoice.
 *
 * Sponsored by: Norwegian Centre for Telemedicine
 * Code: falcon
 *
 * @file
 * Multiplechoice question type for the Quiz module.
 *
 */

/**
 * Implements hook_help().
 */
function likert_scale_help($path, $args) {
  if ($path == 'admin/help#likert_scale') {
    return t("
      <p>This module provides a likert scale question type for Quiz.</p>

      <p>The module has three settings.
      <em>Multiple answers</em> allows the quiz taker to select more than one alternative
      (it also allows for the possibility that none of the alternatives are correct).
      Alternatives are selected using checkboxes instead of radio buttons.
      <em>Random order</em> displays the alternatives in random order when quiz is beeing taken.
      <em>Simple scoring</em> gives max score if everything is correct. Zero points otherwise.</p>

      <p>The scoring system in likert is a bit complex. With multiple answers each alternative adds a given number of points to
      the total score if it is chosen, and another number of points is added if the alternative isn't chosen. Both <em>score if chosen</em> and
      <em>score if not chosen</em> may be edited for each alternative by the question creator.
      If multiple answers isn't allowed the score will be set to the <em>score if chosen</em> of the alternative that has been chosen.
      The question is considered correct if the quiz taker gets the maximum amount of points possible for the question.</p>
    ");
  }
}
/**
 * Implements hook_quiz_question_info().
 */
function likert_scale_quiz_question_info() {
  return array(
    'likert_scale' => array(
      'name' => t('Likert Scale question'),
      'description' => t('This provides likert scale questions for use by the Quiz module.'),
      'question provider' => 'LikertScaleQuestion',
      'response provider' => 'LikertScaleResponse',
      'module' => 'quiz_question', // All wrapper functions are in that module.
    ),
  );
}
/**
 * Implements hook_quiz_question_config().
 */
function likert_scale_quiz_question_config() {
  $form['likert_scale_def_num_of_alts'] = array(
    '#type' => 'textfield',
    '#title' => t('Default number of alternatives'),
    '#default_value' => variable_get('likert_scale_def_num_of_alts', 2),
  );
  $form['likert_scale_def_scoring'] = array(
    '#type' => 'radios',
    '#title' => t('Default scoring method'),
    '#description' => t('Choose the default scoring method for questions with multiple correct answers.'),
    '#options' => array(
      0 => t('Give minus one point for incorrect answers'),
      1 => t("Give one point for each incorrect option that haven't been chosen"),
    ),
    '#default_value' => variable_get('likert_scale_def_scoring', 0),
  );
  $form['#validate'][] = 'likert_scale_config_validate';
  return $form;
}

/**
 * Validate the multichoice config form values
 */
function likert_scale_config_validate($form, $form_state) {
  if (!_quiz_is_int($form_state['values']['likert_scale_def_num_of_alts'], 2, 50)) {
    form_set_error('likert_scale_def_num_of_alts', t('The default number of alternatives must be between 2 and 50'));
  }
}

/**
 * Implements hook_theme().
 */
function likert_scale_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'likert_scale') . '/theme';
  return array(
    'likert_scale_creation_form' => array(
      'render element' => 'form',
      'path' => $path,
      'file' => 'likert_scale.theme.inc',
    ),
    'likert_scale_answer_node_view' => array(
      'variables' => array(
        'alternatives' => NULL,
        'show_correct' => NULL,
      ),
      'path' => $path,
      'file' => 'likert_scale.theme.inc',
    ),
    'likert_scale_alternative_creation_table' => array(
      'render element' => 'form',
      'path' => $path,
      'template' => 'likert-scale-alternative-creation-table',
    ),
    'likert_scale_answering_form' => array(
      'render element' => 'form',
      'path' => $path,
      'template' => 'likert-scale-answering-form',
    ),
    'likert_scale_alternative' => array(
      'render element' => 'form',
      'path' => $path,
      'template' => 'likert-scale-alternative',
    ),
  );
}

/**
 * ajax callback function used when adding alternatives to the node-form
 */
function likert_scale_add_alternative_ajax_callback($form, &$form_state) {
  return $form['alternatives'];
}

/**
 * Implements hook_user_cancel().
 */
function likert_scale_user_cancel($edit, $account, $method) {
  db_delete('quiz_likert_scale_user_settings')
  ->condition('uid', $account->uid)
  ->execute();
}

/**
 * Implements hook_field_extra_fields().
 */
function likert_scale_field_extra_fields() {
  $extra['node']['likert_scale'] = array(
    'form' => array(
      'alternatives' => array(
        'label' => t('Alternatives'),
        'description' => t('Alternatives for likert scale'),
        'weight' => -4,
      ),
    ),
  );
  return $extra;
}

/**
 * Implements hook_views_api().
 */
function likert_scale_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'likert_scale'),
  );
}
